=== OrganizationXV/kingdombutts/application/Data/schedule.dtd
<!-- 
DTD for: winter2016-day.xml, winter2016-time.xml, and winter2016-course.xml.
-->

<!ELEMENT schedule (day, time, course)+>

<!-- 
Each day element contains a specific day of the week (excluding weekend).
-->
<!ELEMENT day (dayz)*>

<!-- 
Each dayz element contains day booking of certain course.
-->
<!ELEMENT dayz (dayBooking)*>
<!ATTLIST dayz
    weekday (Monday|Tuesday|Wednesday|Thursday|Friday) #REQUIRED
>

<!-- Each dBooking element contains:
timeStart   - starting time,
timeEnd     - dismissal time,
courseName  - name of the scheduled course at that time slot,
room        - where the scheduled course will be held, and
instructor  - who teaches the scheduled course
-->
<!ELEMENT dayBooking (timeStart, timeEnd, courseName, room, instructor)*>

<!-- 
time element contains timeslot available for course times
-->
<!ELEMENT time (timeslot)*>

<!-- 
timeslot element contains time booking certain courses.
-->
<!ELEMENT timeslot (timeBooking)*>
<!ATTLIST timeslot
    duration CDATA #REQUIRED
    start CDATA #REQUIRED
    end CDATA #REQUIRED
>

<!-- 
Each pBooking element contains:
daySlot     - weekday slot,
courseName  - name of the scheduled course at that weekday slot,
room        - where the scheduled course will be held, and
instructor  - who teaches the scheduled course
-->
<!ELEMENT timeBooking (daySlot, courseName, room, instructor)*>

<!-- 
 course elements contains courses available in the term
-->
<!ELEMENT course (aCourse)*>

<!-- 
aCourse elements contains course booking at a certain day and time.
-->
<!ELEMENT aCourse (courseBooking)*>
<!-- 
code = unique program course id 
name = course name
-->
<!ATTLIST aCourse
    code CDATA #REQUIRED
    name CDATA #REQUIRED
>

<!-- 
Each cBooking element contains:
timeStart   - starting time,
timeEnd     - dismissal time,
daySlot     - weekday slot,
room        - where the scheduled course will be held, and
instructor  - who teaches the scheduled course
-->
<!ELEMENT courseBooking (daySlot, timeStart, timeEnd, room, instructor)*>
<!-- type refers to course type -->
<!ATTLIST courseBooking
    type (Lab|Lecture|Tutorial) #REQUIRED
>

<!-- Elements containing no children -->
<!ELEMENT timeStart (#PCDATA)*>
<!ELEMENT timeEnd (#PCDATA)*>
<!ELEMENT daySlot (#PCDATA)*>
<!ELEMENT courseName (#PCDATA)*>
<!ELEMENT room (#PCDATA)*>
<!ELEMENT instructor (#PCDATA)*>

=== OrganizationXV/kingdombutts/Data/winter2016-day.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- winter2016-day.xml
     Simon Su, Mark Khauv -->

<!DOCTYPE day SYSTEM 'schedule.dtd'>

<day>
    <dayz weekday="Monday">
        <dayBooking>
            <timeStart>1030</timeStart>
            <timeEnd>1220</timeEnd>
            <courseName>Content Management Systems Admin Lab</courseName>
            <room>SE12-306</room>
            <instructor>Medhat Elmasry</instructor>
        </dayBooking>
        
        <dayBooking>
            <timeStart>1630</timeStart>
            <timeEnd>1720</timeEnd>
            <courseName>Content Mananagement Systems Admin Lecture</courseName>
            <room>SE6-205</room>
            <instructor>Medhat Elmasry</instructor>
        </dayBooking>
    </dayz>
    
    <dayz weekday="Tuesday">
        <dayBooking>
            <timeStart>830</timeStart>
            <timeEnd>1020</timeEnd>
            <courseName>Enterprise Systems Admin Lab</courseName>
            <room>SE12-306</room>
            <instructor>Bethany Edmunds</instructor>
        </dayBooking>
        
        <dayBooking>
            <timeStart>1230</timeStart>
            <timeEnd>1320</timeEnd>
            <courseName>Content Management Systems Admin Lecture</courseName>
            <room>SW9-206</room>
            <instructor>Medhat Elmasry</instructor>
        </dayBooking>
        
        <dayBooking>
            <timeStart>1530</timeStart>
            <timeEnd>1720</timeEnd>
            <courseName>Enterprise Systems Admin Lecture</courseName>
            <room>SW3-3615</room>
            <instructor>Bethany Edmunds</instructor>
        </dayBooking>
    </dayz>
    
    <dayz weekday="Wednesday">
        <dayBooking>
            <timeStart>1230</timeStart>
            <timeEnd>1420</timeEnd>
            <courseName>Integrative Programming and Technologies Lecture</courseName>
            <room>SW3-1750</room>
            <instructor>James Parry</instructor>
        </dayBooking>
    </dayz>
    
    <dayz weekday="Thursday">
        <dayBooking>
            <timeStart>1330</timeStart>
            <timeEnd>1520</timeEnd>
            <courseName>Integrative Programming and Technologies Lab</courseName>
            <room>SE12-306</room>
            <instructor>James Parry</instructor>
        </dayBooking>
    </dayz>
</day>

=== OrganizationXV/kingdombutts/Data/winter2016-course.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- winter2016-course.xml
     Simon Su, Mark Khauv -->

<!DOCTYPE course SYSTEM 'schedule.dtd'>

<course>
    <aCourse code="ACIT4620" name="Enterprise Systems Administration">
        <courseBooking type="Lecture">
            <daySlot>Monday</daySlot>
            <timeStart>1230</timeStart>
            <timeEnd>1320</timeEnd>
            <room>SW1-2009</room>
            <instructor>Bethany Edmunds</instructor>
        </courseBooking>
        <courseBooking type="Lab">
            <daySlot>Tuesday</daySlot>
            <timeStart>0830</timeStart>
            <timeEnd>1020</timeEnd>
            <room>SE12-306</room>
            <instructor>Bethany Edmunds</instructor>
        </courseBooking>
        <courseBooking type="Lecture">
            <daySlot>Tuesday</daySlot>
            <timeStart>1530</timeStart>
            <timeEnd>1620</timeEnd>
            <room>SW3-3615</room>
            <instructor>Bethany Edmunds</instructor>
        </courseBooking>
    </aCourse>
    
    <aCourse code="ACIT4650" name="Content Management Systems Administration">
        <courseBooking type="Lab">
            <daySlot>Monday</daySlot>
            <timeStart>1030</timeStart>
            <timeEnd>1220</timeEnd>
            <room>SE12-306</room>
            <instructor>Medhat Elmasry</instructor> 
        </courseBooking>
        <courseBooking type="Lecture">
            <daySlot>Monday</daySlot>
            <timeStart>1630</timeStart>
            <timeEnd>1720</timeEnd>
            <room>SE6-205</room>
            <instructor>Medhat Elmasry</instructor>
        </courseBooking>
        <courseBooking type="Lecture">
            <daySlot>Tuesday</daySlot>
            <timeStart>1230</timeStart>
            <timeEnd>1320</timeEnd>
            <room>SW9-206</room>
            <instructor>Medhat Elmasry</instructor>
        </courseBooking>
    </aCourse>
    
    <aCourse code="ACIT4850" name="Integrative Programming and Technologies">
        <courseBooking type="Lecture">
            <daySlot>Wednesday</daySlot>
            <timeStart>1230</timeStart>
            <timeEnd>1420</timeEnd>
            <room>SW3-1750</room>
            <instructor>James Parry</instructor>
        </courseBooking>
        <courseBooking type="Lab">
            <daySlot>Thursday</daySlot>
            <timeStart>1330</timeStart>
            <timeEnd>1520</timeEnd>
            <room>SE12-308</room>
            <instructor>James Parry</instructor>
        </courseBooking>
    </aCourse>
</course>

=== OrganizationXV/kingdombutts/application/Data/winter2016-time.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE time SYSTEM 'schedule.dtd'>

<time>
    <timeslot duration="2" start="830" end="1020">
    <timeBooking>
        <daySlot>Tuesday</daySlot>
        <courseName>Enterprise Systems Admin Lab</courseName>
        <room>SE12-306</room>
        <instructor>Bethany Edmunds</instructor>
    </timeBooking>
    </timeslot>
    
    <timeslot duration="2" start="1030" end="1220"> 
    <timeBooking> 
        <daySlot>Monday</daySlot>
        <courseName>Content Management Systems Admin Lab</courseName>
        <room>SE12-306</room>
        <instructor>Medhat Elmasry</instructor>
    </timeBooking>
    </timeslot>
    
    <timeslot duration="1" start="1230" end="1320"> 
    <timeBooking>
        <daySlot>Monday</daySlot>
        <courseName>Enterprise Systems Admin Lecture</courseName>
        <room>SW1-2009</room>
        <instructor>Bethany Edmunds</instructor>
        
        <daySlot>Tuesday</daySlot>
        <courseName>Content Management Systems Admin Lecture</courseName>
        <room>SW9-206</room>
        <instructor>Medhat Elmasry</instructor>
    </timeBooking>
    </timeslot>
    
    <timeslot duration="2" start="1230" end="1420"> 
    <timeBooking>
        <daySlot>Wednesday</daySlot>
        <courseName>Integrative Programming and Technologies Lecture</courseName>
        <room>SW3-1750</room>
        <instructor>James Parry</instructor>
    </timeBooking>
    </timeslot>
    
    <timeslot duration="2" start="1330" end="1520"> 
    <timeBooking> 
        <daySlot>Thursday</daySlot>
        <courseName>Integrative Programming and Technologies Lab</courseName>
        <room>SE12-308</room>
        <instructor>James Parry</instructor>
    </timeBooking>
    </timeslot>
    
    <timeslot duration="1" start="1530" end="1620"> 
    <timeBooking>
        <daySlot>Tuesday</daySlot>
        <courseName>Enterprise Systems Admin Lecture</courseName>
        <room>SW3-3615</room>
        <instructor>Bethany Edmunds</instructor>
    </timeBooking>
    </timeslot>
    
    <timeslot duration="1" start="1630" end="1720"> 
    <timeBooking>
        <daySlot>Monday</daySlot>
        <courseName>Content Management Systems Admin Lecture</courseName>
        <room>SE6-205</room>
        <instructor>Medhat Elmasry</instructor>
    </timeBooking>
    </timeslot>
</time>
